name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: gradle

    - name: Create local.properties
      run: |
        echo "sdk.dir=$ANDROID_SDK_PATH" > local.properties
        echo "kakao_NATIVE_APP_KEY=$KAKAO_NATIVE_APP_KEY" >> local.properties
        echo "kakao_NATIVE_APP_KEY_MANIFEST=$KAKAO_NATIVE_APP_KEY_MANIFEST" >> local.properties
      env:
        ANDROID_SDK_PATH: ${{ secrets.ANDROID_SDK_PATH }}
        KAKAO_NATIVE_APP_KEY: ${{ secrets.KAKAO_NATIVE_APP_KEY }}
        KAKAO_NATIVE_APP_KEY_MANIFEST: ${{ secrets.KAKAO_NATIVE_APP_KEY_MANIFEST }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
